#!/bin/bash

# First parameter is the sub-directory-absolute-path
# Second parameter is the link of the repo
# Third parameter is the branch of the repo
# sh subdirGit.sh <subdir-path> https://github.com/<user>/<repo> <branch>

# A smart split to get the repo-name, with / as a separator
REPO_NAME="$(echo $2 | grep -oE '[^/]+$')"

git init $REPO_NAME
cd $REPO_NAME

git remote add origin $2
git config core.sparsecheckout true

# Specipy the sub directory
echo "$1/*" >> .git/info/sparse-checkout
# then get it..
git pull origin $3

## For getting only the sub-directory
# If you want to work with the repo, comment following lines
mv $1 ../$1
cd ../
rm -rf $REPO_NAME
